---
title: "Trichy Weather Analysis"
author: "Andrew Mertens"
date: "October 22, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Abstract

  *  Subject Background  
  *  Study Background
  * 

```{r cars}
summary(cars)
```


##Setup
```{r}
library(foreign)
library(dplyr)
library(SuperLearner)
library(tmle)
library(tmle.npvi)

```


## Summary of the survey data

Load in the data and conduct exploratory analysis
```{r}
#read in data and subset to relevant variables
svy<-read.dta("trichy_long_old.dta") %>%
  subset(select=c("vilid","hhid","individ","wpi","round","intdate","studywk","bdate","age","sex",
                  "bfcur","sanOD","sanlat","primwat",
                  "soil","thatch","radio","tv","cell","bank","moto","bike","mosq","stove","fuel1", #assets
                  "anygrp","shgw","agri","elec","land","ownhome",
                  "pceduc","pclit","momage","momwork", # education
                  "rooms","totp","sc","kitchen","kitchvent", #house
                  "hwflies","hwwater","hwsoap","hwash","hwtow","hwsink","hwcntwat","hwcntsoap" #handwashing station
                  ,"hw1","hw2","hw3","hw4","hw5","hw6","hw7","hw8","hw9","hw10","hw11","hw12", #handwash w/ water
                  "hws1","hws2","hws3","hws4","hws5","hws6","hws7","hws8","hws9","hws10","hws11","hws12", #handwash w/soap
                  "boil_freq","boil_ready","boil_min","boil_present","wqsource","wqcol","wqdate","wstore","wboil", #watertreat
                  "ecoli","log10ecoli","tc","log10tc","dilution","h2s", #water treatment
                  "mdiar7d","diar7d","hcgi7d","diardays", #diarrea outcome variables.
                  "latage","latfinance","latused","lathole","latwat","latsoap","latflies","latfec", #latrine quality
                  "an_buff","an_cow","an_ox","an_calf","an_goat","an_chick", #household animals
                  "an_dogcat","stockliv","goatliv","chickliv","dogcatliv", #household animals
                  
                  
                  "fecesliv","fecessm","chobs_hand","chobs_nails","chobs_face","chobs_cloth","chobs_nocloth","chobs_shoes","wgt","hgt","hgtm","uac","F1","qF1"
                  
                  
                  
                  )) %>%#_old is file "trichy_long.dta" saved in Stata 12 format

glimpse(svy)
```


## Summary of the weather data


Load in data

